export const CREATE_TASK = "CREATE_TASK";

export const UPDATE_STATUS_READY = "UPDATE_STATUS_READY"
export const UPDATE_STATUS_SUBMITTING = "UPDATE_STATUS_SUBMITTING"
export const UPDATE_STATUS_ERROR = "UPDATE_STATUS_ERROR"
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS"

export const UPDATE_NETWORK = "UPDATE_NETWORK"
